add tmp, and finished 32x32 ar icon
rizmut/libreoffice-style-sifr pull request #1
Opened 2019-11-03 11:41 UTC by arivle

2019-11-04 13:17 UTC, rizmut requested changes
Tolong perhatikan kesesuaian batas-batas ikon dengan grid 0,5px*0,5px dengan garis kisi utama setiap 2 (dua buah)

2019-11-14 11:23 UTC, arivle commented
https://github.com/rizmut/libreoffice-style-sifr/pull/1#pullrequestreview-311060261
baru /ar sama /ca yang saya sesuaikan dengan grid, mohon di cek

2019-12-27 07:46 UTC, rizmut requested changes
Tolong hilangkan semua kapitalisasinya ya.

Sama gak usah dibuat subfolder baru kalau bisa ke depannya.

Tolong beberapa ikon ini dipaskan kembali ke dalam kisinya:

ArrowShapesquad-arrow.svg (garis panah)
CommentChange.svg (bagian dalam kotaknya)
DeleteComment.svg (bagian dalam kotaknya)
DataSubTotals.svg (kotak-kotaknya)
GoalSeekDialog.svg (bagian dalam filternya)
InsertColumnsAfter.svg (tanda tambahnya)
SetDocumentProperties.svg (bagian dalam kertas/doknya, oh ya kertasnya terlalu lebar kayaknya)
ShareDocument.svg (bagian dalam kertas/doknya, SetDocumentProperties.svg)
ShowDependents.svg (bagian dalam kotaknya)
SplitCell.svg (kotak paling tengah)
SortAscending.svg (A sama Z)
TextToColumn.svg (sama kayak SetDocumentProperties.svg dengan bagian kotak sheet juga gak pas . Oh ya, pastikan samakan bentuknya sama versi 24px sama 16px, saya lihat panahnya hilang)

2019-12-27 07:52 UTC, rizmut commented
> [#1 (review)](https://github.com/rizmut/libreoffice-style-sifr/pull/1#pullrequestreview-311060261)
> baru /ar sama /ca yang saya sesuaikan dengan grid, mohon di cek

sisanya masih ada yang belum pas sama kisi ya, tolong diperbaharui

2022-02-22 14:45 UTC, closed without merging